#!/bin/bash

# Copyright 2014 Bryan Garber
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

volume_step=4

if [ ! $# -eq 0 ]; then
    case $1 in
    "inc")
        res=$(amixer -D pulse set Master $volume_step%+ | sed -n 's/.*Front Left.*\[\([0-9]\+%\)\].*/\1/p')
        ;;
    "dec")
        res=$(amixer -D pulse set Master $volume_step%- | sed -n 's/.*Front Left.*\[\([0-9]\+%\)\].*/\1/p')
        ;;
    "tog")
        res=$(amixer -D pulse set Master toggle | sed -n 's/.*Front Left.*\[\([a-z]\+\)\].*/\1/p')
        if [ $res = "on" ]; then
            res="Unmute"
        elif [ $res = "off" ]; then
            res="Mute"
        fi
        ;;
    *)
        res="Unknown command."
    esac
    notify-send "Volume: $res"
fi
