#!/bin/bash

# Copyright 2014 Bryan Garber
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.


if [ ! $# -eq 0 ]; then
    rhythm=$(pgrep -u $USER rhythmbox)
    banshee=$(pgrep -u $USER banshee)
    clementine=$(pgrep -u $USER clementine)

    if [ $rhythm ]; then
        player="rhythmbox"
    elif [ $banshee ]; then
        player="banshee"
    elif [ "$clementine" ]; then
        player="clementine"
    fi

    case $1 in
    "play")
        dbus-send --session --dest=org.mpris.MediaPlayer2.$player \
            --type=method_call /org/mpris/MediaPlayer2 \
            org.mpris.MediaPlayer2.Player.PlayPause
        ;;
    "stop")
        dbus-send --session --dest=org.mpris.MediaPlayer2.$player \
            --type=method_call /org/mpris/MediaPlayer2 \
            org.mpris.MediaPlayer2.Player.Stop
        ;;
    esac
fi

